### ISSUE TITLE
 fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory

### ISSUE THREAD

**Issue by TheBlindM** [graalvm/graalvm-demos#108]
Packaging exception under windows
JDK 11
GraalVM 21.3.1
VS 2019

C++/CLI v142 Build Tools latest version
MSVC v142 - VS 2019 C++ x64/x86  Build Tools latest version
Windows Universal CRT SDK
Windows 10 SDK Build Tools latest version

`[demo1-1.0-SNAPSHOT-runner:18388]        setup:     703.39 ms,  0.94 GB
Error: Error compiling query code (in C:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.c). Compiler command ''C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.exe' 'C:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.c'' output included error: [BuiltinDirectives.c, C:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.c(1): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory]
com.oracle.svm.core.util.UserError$UserException: Error compiling query code (in C:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.c). Compiler command ''C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe' /WX /W4 /wd4244 /wd4245 /wd4800 /wd4804 /wd4214 '/FeC:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.exe' 'C:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.c'' output included error: [BuiltinDirectives.c, C:\Users\NINGMEI\AppData\Local\Temp\SVM-4604528042326155277\BuiltinDirectives.c(1): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory]
        at com.oracle.svm.core.util.UserError.abort(UserError.java:144)
        at com.oracle.svm.hosted.c.NativeLibraries.reportErrors(NativeLibraries.java:370)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1571)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1046)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:869)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:527)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[demo1-1.0-SNAPSHOT-runner:18388]      [total]:   2,422.16 ms,  0.94 GB
# Printing build artifacts to: D:\study\demo1\target\demo1-1.0-SNAPSHOT-native-image-source-jar\demo1-1.0-SNAPSHOT-runner.build_artifacts.txt
Error: Image build request failed with exit status 1
[IJ]-1-MojoFailed-[IJ]-source=LIFECYCLE-[IJ]-goal=build-[IJ]-id=com.example:demo1:jar:1.0-SNAPSHOT-[IJ]-error=Image generation failed. Exit code: 1`

**Comment by olyagpl** [comment]
Since there is no feedback for a long time,  we assume you could overcome the problem and close this issue.
