### ISSUE TITLE
Error Illegal char <> at index 3: occuring while trying to build native executable for the project spring-native-image

### ISSUE THREAD

**Issue by nigelthomas-mozanta** [graalvm/graalvm-demos#150]
An error is occurring while trying to build the native executable for the project **spring-native-image** using the maven command

`mvn -Pnative native:compile`

Below is the error which is being logged.

```
Executing: C:\Softwares\graalvm-ce-java17-22.3.0\bin\native-image.cmd @target\tmp\native-image-12404653925673489780.args
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <> at index 3: C:\Development\Notes\GraalVM\demo\graalvm-demos\spring-native-image\target\classes
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@17.0.5/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@17.0.5/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:52)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1582)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:69)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:204)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1770)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:959)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```

**Comment by nigelthomas-mozanta** [comment]
### **Update**

I created a Micronaut app as well and tried to build the native executable using the command.

`gradlew nativeCompile`


There also the same error is occurring.

```
 > Task :nativeCompile FAILED
[native-image-plugin] Toolchain detection is disabled, will use GraalVM from C:\Softwares\graalvm-ce-java17-22.3.0.
[native-image-plugin] Using executable path: C:\Softwares\graalvm-ce-java17-22.3.0\bin\native-image.cmd
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <> at index 3: C:\Development\Notes\GraalVM\demo\graalvm-demos\micronaut-hello\build\libs\micronaut-hello-0.1.jar
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base@17.0.5/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base@17.0.5/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base@17.0.5/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base@17.0.5/java.nio.file.Path.of(Path.java:147)
        at java.base@17.0.5/java.nio.file.Paths.get(Paths.java:69)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.ClasspathUtils.stringToClasspath(ClasspathUtils.java:52)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.addCustomImageClasspath(NativeImage.java:1582)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.processClasspathArgs(DefaultOptionHandler.java:417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:69)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.DefaultOptionHandler.consume(DefaultOptionHandler.java:204)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1512)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1770)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:959)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
        at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```

**Comment by olyagpl** [comment]
Hi @nigelthomas-mozanta. It must be a Windows-only issue.  Are you building the native executable within a Docker container? This demo is being successfully tested on the latest Ubuntu. For OS other than Linux, you build the native executable within a container.

**Comment by fniephaus** [comment]
This seems related to https://github.com/graalvm/native-build-tools/issues/318.

**Comment by olyagpl** [comment]
@nigelthomas-mozanta, the possible cause was resolved in https://github.com/oracle/graal/pull/5725. If you run this app on the [latest GraalVM 22.3 release](https://docs.oracle.com/en/graalvm/enterprise/22/docs/release-notes/#release-notes) and the problem persists, please reopen the bug.
