### ISSUE TITLE
Building native-image from java-simple-stream-benchmark gives exception

### ISSUE THREAD

**Issue by ghost** [graalvm/graalvm-demos#19]
I am able to build and run java-simple-stream-benchmark using graalvm-ee-1.0.0-rc9. The benchmark results are better using graalvm so I assume that everything is working correctly.

Building a native image using the native-image utility in graalvm also works as expected but does give the following warning multiple times:

`Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.openjdk.jmh.runner.InfraControl. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. `

When I run the native-image, this is my stack trace: 

`Exception in thread "main" java.lang.IllegalArgumentException: class org.openjdk.jmh.runner.options.TimeValue is not a value type
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
	at joptsimple.internal.Reflection.findConverter(Reflection.java:66)
	at joptsimple.ArgumentAcceptingOptionSpec.ofType(ArgumentAcceptingOptionSpec.java:106)
	at org.openjdk.jmh.runner.options.CommandLineOptions.<init>(CommandLineOptions.java:109)
	at org.openjdk.jmh.Main.main(Main.java:41)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
`

**Comment by olyagpl** [comment]
This problem has been already resolved. Please use more recent GraalVM versions.
Closing this issue. Thanks for the report!
