### ISSUE TITLE
Permisison Denied Exception when running ListDir demo on RHEL 7

### ISSUE THREAD

**Issue by lloydfischer-wc** [graalvm/graalvm-demos#51]
After installing graalvm-ce-java11-19.3.1 I cloned demos using git clone https://github.com/graalvm/graalvm-demos

Executing build.sh resulted in the following exception. I'm able to write into the /tmp directory so I have to assume that the executable is not written with the correct permisions. It is deleted before I can see it. 

Build on Server(pid: 7003, port: 39868)*
[listdir:7003]    classlist:   1,854.66 ms
[listdir:7003]        (cap):     328.89 ms
[listdir:7003]        setup:     627.65 ms
Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.io.IOException: Cannot run program "/tmp/SVM-17161308199606515702/LibFFIHeaderDirectives" (in directory "/tmp/SVM-17161308199606515702"): error=13, Permission denied
        at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:114)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.process(CAnnotationProcessor.java:89)
        at com.oracle.svm.hosted.c.NativeLibraries.finish(NativeLibraries.java:377)
        at com.oracle.svm.hosted.NativeImageGenerator.processNativeLibraryImports(NativeImageGenerator.java:1517)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1006)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:835)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.io.IOException: Cannot run program "/tmp/SVM-17161308199606515702/LibFFIHeaderDirectives" (in directory "/tmp/SVM-17161308199606515702"): error=13, Permission denied
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.startCommand(CCompilerInvoker.java:146)
        at com.oracle.svm.hosted.c.CAnnotationProcessor.makeQuery(CAnnotationProcessor.java:105)
        ... 13 more
Caused by: java.io.IOException: error=13, Permission denied
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 16 more
Error: Image build request failed with exit status 1

**Comment by carljmosca** [comment]
We do not have exec permission on files in /tmp

**Comment by Futurile** [comment]
I just ran into this as I have my /tmp mounted with noexec for security reasons. I'm on Ubuntu, but it's not distribution specific. Check /etc/fstab for mount options. 

The solution was to set some options for Java:

```
export _JAVA_OPTIONS=-Djava.io.tmpdir=/path/to/a/tmpdir
```

There's an extensive discussion on [Java and tmpdir](https://stackoverflow.com/questions/1924136/environment-variable-to-control-java-io-tmpdir) on Stackoverflow, including why you can't use TMPDIR.

**Comment by olyagpl** [comment]
@lloydfischer-wc, since this isn't a GraalVM issue, but platform specific, we are closing this.
