### ISSUE TITLE
scala-examples: issue with building and running scala-native substitution demo

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/graalvm-demos#97]
On the back of the PR #93, building and running the scala-native substitution demo gives an issue after following the steps in the README were followed, see https://github.com/graalvm/graalvm-demos/tree/master/scala-examples/scalac-native#native-image-of-the-scala-compiler.

Running the step `./scalac-image.sh` gives the below error:

```
root@b41b00dc8fec:/graalvm-demos/scala-examples/scalac-native# ./scalac-image.sh -H:+ReportExceptionStackTraces
[scalac:220]    classlist:  25,162.81 ms,  0.96 GB
Error: Main entry point class 'scala.tools.nsc.Main' not found.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'scala.tools.nsc.Main' not found.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:323)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[scalac:220]      [total]:  25,444.44 ms,  0.96 GB
Error: Image build request failed with exit status 1
```
The original contributor to the example has been contacted and help has been sought to help fix this issue when running with the latest version of GraalVM CE.

**Comment by olyagpl** [comment]
If you use GraalVM on Java 11 or 17, you would see this notice printed:
`This demo works only with Java 8. Set your JAVA_HOME to a JDK 8 version.`
I've merged the PR from 
Vojin Jovanovic: https://github.com/graalvm/graalvm-demos/pull/98:

**Comment by olyagpl** [comment]
This example application is no longer maintained. I'm closing this issue.
